---
- name: Get the basic software installed
  apt:
    state: present
    name:
      - git
      - zsh
      - network-manager

- name: Find the location of zsh shell
  command: which zsh
  register: zsh_location

- name: Display zsh location
  debug: 
    var: zsh_location.stdout

- name: Change shell to zsh
  user:
    name: "{{ username }}"
    shell: "{{ zsh_location.stdout }}"
  become: true